### ISSUE TITLE
Handling of Large Numbers (IEEE754 Compatible)

### ISSUE THREAD

**Issue by texttechne** [odata2ts/odata2ts#106]
The following two data types of OData are  64-bit binary format IEEE 754 values, which might actually not fit into the JS number type: 
* `Edm.Int64`
* `Edm.Decimal`

While V2 represents these numbers as `string` (among many other number types), V4 represents all number types as `number`. V4 has a special format setting to handle both mentioned number types as strings:
* the format value is always `application/json;IEEE754Compatible=true` 
* querying / retrieving IEEE 754 compatible numbers
  * see [Spec: Requesting the JSON Format](https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_RequestingtheJSONFormat)
  * set format via query param `$format` or `Acccept` header 
  * the `Content Type` header of the response will have the format
* sending IEEE 754 compatible numbers (POST, PUT, PATCH) 
  * see [Spec: Header Content Type](https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_HeaderContentType)
  * set `Content-Type` header (of the request) to the format
  * the `Content-Type` header of the response will have the format, if not empty

## Tasks
- [x] generator: add global configuration option so that all requests use the IEEE 754 format by default
- [x] generator: map `Edm.Int64` and `Edm.Decimal` to `string` when generating models
- [x] extend `http-client-api` and `http-client-base` which set the correct headers
  - approach: setter on http client which is called by each service
  - one call to the setter would be enough, but then it works for usage with individual services not instantiated by main service
- [x] generator: when generating services, make use of new http client setter 
- [x] ~~V4 only: add format option to `query builder` so that individual resquests may or may not use the IEEE 754 format~~
- [x] Converter `Int64` to `BigInt` 
  - common converter package

**Comment by texttechne** [comment]
Released with:
* ´@odata2ts/odata2ts` version `0.28.0`
* ´@odata2ts/odata-service` version `0.16.0`
* ´@odata2ts/odata-query-objects` version `0.19.0`
* ´@odata2ts/http-client-api` version `0.3.0`
* ´@odata2ts/http-client-axios` version `0.8.1`
* ´@odata2ts/http-client-fetch` version `0.3.1`
* ´@odata2ts/http-client-jquery` version `0.5.1`

Additionally the following converters have been added:
* ´@odata2ts/converter-big-number` version `0.0.1`
* ´@odata2ts/converter-decimal` version `0.0.1`
