### ISSUE TITLE
Handle Managed Props

### ISSUE THREAD

**Issue by texttechne** [odata2ts/odata2ts#15]
The entity types that are declared in the metadata define the properties of each attribute, e.g. its type or if its required or optional. However, regarding the typical CRUD operations we're missing one central piece of information: Is an attribute managed / generated on the server side?

When a prop is managed, the client may not edit this property and so it should not occur in the editable version of the generated model interface of the respective entity. The following operations are affected: Create, Update, Patch.

Typical use cases for managed props:
* Id field
* createdAt, createdBy, modifiedAt, modifiedBy

## Tasks
- [x] provide property configuration which allows to set `managed` flag
- [x] generation process for `EditableModel` respects `managed` flag
- [ ] automatically set `managed` flags
  - logic: single key = managed, composite key = unmanaged 
  - provide configuration to disable automatism

### Notes
Services may add annotations to promote this information. But since this information is service specific then, it is out-of-scope for the current issue.

**Comment by texttechne** [comment]
Can already be tackled by configuration `propertyByName` and more specifically the setting `managed`. As soon as an attribute is marked as managed, it won't appear in the Editable model version used for create / update / patch.
