### ISSUE TITLE
[Feature Request]OData V3 Support

### ISSUE THREAD

**Issue by szarcensky** [odata2ts/odata2ts#224]
As V3 and V4 response types are similar, requesting support for V3.

Both are using `value` to hold the data, but V3 uses `odata.metadata` instead of `@odata.context`, and `odata.count` instead of `@odata.count`. Paging also using `odata.nextLink` instead of `@odata.nextLink`, so mostly it's not using the `@` prefix.

[Northwind V3](https://services.odata.org/V3/Northwind/Northwind.svc/Customers?$format=json)
[Northwind V4](https://services.odata.org/V4/Northwind/Northwind.svc/Customers?$format=json)

**Comment by texttechne** [comment]
## TODO List for V3 Support

- [ ] Detect V3
- [ ] Throw error for unsupported versions

### EDMX Capabilities
AFAIK V3 introduced `ComplexType` and `EnumType`, maybe also collection of primitve values.
This should be supported already, but I should check again:
- [ ] Support ComplexType
- [ ] Support EnumType
- [ ] Support Collection of Primtive Values?

### HTTP capabilities
- [ ] use PATCH instead of MERGE (like V4)

### Response Structures
- [ ] use V4 response structures

Differences:
- Entity Response: like v4, but
    - `odata.metadata` instead of `@odata.context`
- Entity Collection Response: like v4, but
    - `odata.metadata` instead of `@odata.context`
    - `odata.count` instead of `@odata.count`
    - `odata.nextLink` instead of `@odata.nextLink`

---
However, the specification should be checked thoroughly. @szarcensky you're very welcome to point out more differences!

**Comment by szarcensky** [comment]
A few differences that seemed relevant from V3 to V4

`OData-Version` replaced `DataServiceVersion`
`OData-MaxVersion` replaced `MaxDataServiceVersion`
`OData-EntityId` replaced `DataServiceId`

`$inlinecount=allpages` has been shortened to `$count=true`
V3 doesn't support `$search`

[What’s New in OData Version 4.0](https://docs.oasis-open.org/odata/new-in-odata/v4.0/cn01/new-in-odata-v4.0-cn01.html)

**Comment by texttechne** [comment]
Hi @szarcensky,

in the [original discussion](https://github.com/odata2ts/odata2ts/discussions/217#discussioncomment-7148647) you stated:
> my service is v3. The class structure is expecting the response in the format `response.data.d.results` but what's coming back from the odata service is in the format `response.data.value`

You also pointed to the "official" sample V3 odata service as example: [Northwind V3] (https://services.odata.org/V3/Northwind/Northwind.svc/Customers?$format=json). It behaves the way you say.

However, according to [the V3 spec on response structures](https://www.odata.org/documentation/odata-version-3-0/json-verbose-format/#responsespecifics) they should definitely align with V2. This would mean that the response of Northwind V3 is plainly wrong. The specification always wins and this is to be assumed weired behaviour then.

As you are concerned with your very own implementation of an OData service, how comes that you return that kind of response structure?

**Comment by texttechne** [comment]
Hi @szarcensky,

ok, [this article sheds some light on what is happening](https://learn.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v3/creating-an-odata-endpoint#formats):
> OData supports several serialization formats:
> * Atom Pub (XML)
> * JSON "light" (introduced in OData v3)
> * JSON "verbose" (OData v2)
>
> By default, Web API uses AtomPubJSON "light" format.

The funny thing is that this differentiation between "ligth" and "verbose" JSON format is never explicitly discussed in any of the official documents (well, at least I cannot find it). And there only exists a specification for the **verbose format**, which I was referencing above. In there I can now found this section:
> Verbose JSON is not the default OData format. To receive responses in Verbose JSON, the client MUST explicitly ask for them.
>
> To request this format using $format, use the value jsonverbose. To request this format using the Accept header, use the MIME type application/json;odata=verbose.

So for you it would be as easy as 
```
new FetchClient({headers: { Accept: "application/json;odata=verbose" }) // same would hold true for the other HTTP clients
```

I'm adding an appropriate todo in the list above.

**Comment by Shmookoff** [comment]
Hey. Is there any progress on this? Maybe, any tips on hacking together something for this library to work with v3?

**Comment by szarcensky** [comment]
> Hey. Is there any progress on this? Maybe, any tips on hacking together something for this library to work with v3?

@Shmookoff the main issue I had using V3 was the data coming back in the `response.data.value` format, when the library's V2 support is expecting `response.data.d.results`. If your V3 uses the other format, which it optionally can, you may not have that issue at all. I found that if I cast the promise response to `any`, and referenced the data using the `response.data.value` format, I was able to get and use V3 responses without any errors. Of course, this is non ideal if you're expecting a third party user to use the generated code, as you'd need them to use this technique.

**Comment by texttechne** [comment]
Hi @Shmookoff,

what's your use case: model generation or full odata client?

**Comment by Shmookoff** [comment]
@szarcensky Sadly, my OData provider uses the `response.data.value` format. However, I don't want to give up type safety the library provides.. I suppose I can force it to use `response.data.d.results` using some wrapper (maybe a proxy server that just alters the format; translation layer) around the OData provider. Is there any other issues I should be aware of?

**Comment by Shmookoff** [comment]
Hello, @texttechne. Full OData client.

**Comment by texttechne** [comment]
Hi @Shmookoff,

then your biggest problem is the response structure, I guess.
The workaround is:

```
new FetchClient({headers: { Accept: "application/json;odata=verbose" }) // same would hold true for the other HTTP clients
```

With this setting you get the V2 response structure and odata2ts works in this regard then.

Do you have any other issues of the above mentioned feature list (my first comment in this thread)?
